name: stylesstack_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.9.0
  image_picker: ^0.8.4+4
  provider: ^6.0.0
  crypto: ^3.0.3
  firebase_core: ^2.13.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1  # For storing images
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
